#!/usr/bin/env node
// dsh-scrapling/build-client.ts —— 构建 client.js。
//
// 用 rolldown 把 src/client-entry.ts 打包为 CJS（react 外部化），再包进
// window.__ModuleLoader__.load({ id, factory }) 外壳。id 取 package.json 的 name，
// 与 dsh.client 模块表键一致。
//
// 同步 fs（readFileSync/writeFileSync）为构建必需，已列入 oxlint.config.ts 的 syncWrites。
//
// 与 build-host.ts 同理：**源码是 .ts，产物是 .js** —— Node 不肯在 node_modules 里
// 剥类型，而 dsh 正是在 node_modules 里按包名载入 client.js 的。

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen66/dsh-plugin-shared/lib/canonicalize-region-paths";
import { isRecord } from "@jayyuen66/dsh-plugin-shared/lib/record";

const root = import.meta.dirname;

const pkgJson: unknown = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));

const nameKey = "name";
const nameRaw = isRecord(pkgJson) ? pkgJson[nameKey] : undefined;
const pkgName = typeof nameRaw === "string" ? nameRaw : "unknown";

/**
 * 生成 client.js 的完整文本（含 ModuleLoader 外壳）。
 *
 * @returns 产物文本
 */
export async function buildClient(): Promise<string> {
  const bundle = await rolldown({
    input: path.join(root, "src", "client-entry.ts"),
    external: ["react"],
    platform: "browser",
    resolve: {
      extensions: [".ts", ".mjs", ".js", ".json"],
    },
  });
  const { output } = await bundle.generate({ format: "cjs" });
  const chunk = output.find((item) => item.type === "chunk");
  if (chunk === undefined) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // 见 shared/lib/canonicalize-region-paths.ts：`//#region` 行的路径由 rolldown 按
  // process.cwd() 算出 ⇒ 同一份源码两种字节。折 canonical 必须落在返回值之前
  // （新鲜度测试逐字节比内存构建与磁盘产物）。
  const body = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
  return [
    "// GENERATED by build-client.ts — edit src/client-entry.ts, then run `node build-client.ts`.",
    "window.__ModuleLoader__.load({",
    `  id: '${pkgName}',`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  },",
    "});",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const out = await buildClient();
  writeFileSync(path.join(root, "client.js"), out, "utf8");
  console.info("client.js written:", out.length, "chars");
}

if (process.argv[1] === import.meta.filename) {
  // 这里用顶层 await：node/no-top-level-await 与本文件原本该满足的
  // unicorn/prefer-top-level-await 互斥，已在 oxlint.config.ts 里按「对侧互斥」
  // 记录了关掉哪一条。构建脚本只由 node 直接执行，不进 bundler 的 require(esm) 路径。
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}
